services:
  ui-dev:
    build:
      dockerfile: ./ui/Dockerfile
      target: ui-dev
    environment:
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - ./ui:/app
      - /app/node_modules
  