services:
  api-dev:
    build:
      dockerfile: ./api/Dockerfile
      target: api-dev
    environment:
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
      - /var/archiver:/var/archiver
  ui-dev:
    build:
      dockerfile: ./ui/Dockerfile
      target: ui-dev
    environment:
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - ./ui:/app
      - /app/node_modules
      - /var/archiver:/var/archiver
  dozzle:
    image: amir20/dozzle:latest
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
